version: '3'
services:
  master:
    build: ./master
    volumes:
      - ./scripts:/scripts
    environment:
      - POSTGRESQL_USER=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=test
      - POSTGRESQL_ADMIN_PASSWORD=postgres
  slave:
    build: ./slave
    volumes:
      - ./scripts:/scripts
    environment:
      - POSTGRESQL_USER=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=test
      - POSTGRESQL_ADMIN_PASSWORD=postgres
